# Gravity data sets

```{r}
pacman::p_load(tidyverse, magrittr, here)
```

```{r}
trade_flows <- read_csv(here("Data", "Main data frames", "trade_flows.csv"))
transaction_costs <- read_csv(here("Data", "Main data frames", "transaction_costs.csv"))
gtm_macro <- read_csv(here("Data", "Main data frames", "gtm_macro.csv"))
partners_macro <- read_csv(here("Data", "Main data frames", "partners_macro.csv"))
partners_names <- read_csv(here("Data", "Main data frames", "partners_names.csv"))
```

## 1 --- Gravity (total flows)

### Exports

```{r}
total_exports <- 
  trade_flows %>% 
  filter(trade_flow == "Export") %>% 
  group_by(year, partner_iso) %>% 
  summarise(trade_value = sum(trade_value_usd)) %>% 
  ungroup() %>% 
  arrange(partner_iso)
```

```{r}
total_exports %>% 
  ggplot(aes(year, trade_value)) +
  geom_line() +
  facet_wrap(~ partner_iso, scales = "free")
```

```{r}
# Countries and years for which there are zero trade flows
transaction_costs %>% anti_join(total_exports) %>% View
```

```{r}
exports <- 
  transaction_costs %>% 
  left_join(total_exports) %>% 
  select(year:partner_iso, trade_value, everything()) %>% 
  mutate(across(where(is.numeric), ~ replace(., is.na(.), 0))) %>% 
  left_join(gtm_macro, 
            by = c("year", "reporter_iso")) %>% 
  select(year:rta, "gdp_i" = gdp, "gdp_pcap_i" = gdp_pcap) %>% 
  left_join(partners_macro, 
            by = c("year", "partner_iso")) %>% 
  select(year:gdp_pcap_i, "gdp_j" = gdp, "gdp_pcap_j" = gdp_pcap) %>% 
  rename("iso_i" = reporter_iso, "iso_j" = partner_iso, "exports" = trade_value)
```

### Imports

```{r}
total_imports <- 
  trade_flows %>% 
  filter(trade_flow == "Import") %>% 
  group_by(year, partner_iso) %>% 
  summarise(trade_value = sum(trade_value_usd)) %>% 
  ungroup() %>% 
  arrange(partner_iso)
```

```{r}
total_imports %>% 
  ggplot(aes(year, trade_value)) +
  geom_line() +
  facet_wrap(~ partner_iso, scales = "free")
```

```{r}
# There are 80 zeros in the total_import data set
transaction_costs %>% anti_join(total_imports) %>% View
```

```{r}
imports <- 
  transaction_costs %>% 
  left_join(total_imports) %>% 
  select(year:partner_iso, trade_value, everything()) %>% 
  mutate(across(where(is.numeric), ~ replace(., is.na(.), 0))) %>% 
  left_join(gtm_macro, 
            by = c("year", "reporter_iso")) %>% 
  select(year:rta, "gdp_i" = gdp, "gdp_pcap_i" = gdp_pcap) %>% 
  left_join(partners_macro, 
            by = c("year", "partner_iso")) %>% 
  select(year:gdp_pcap_i, "gdp_j" = gdp, "gdp_pcap_j" = gdp_pcap) %>% 
  rename("iso_i" = reporter_iso, "iso_j" = partner_iso, "imports" = trade_value)
```

### Final data set

```{r}
gravity <- 
  exports %>% 
  select(exports) %>%
  bind_cols(imports) %>% 
  select(year:iso_j, exports, imports, everything()) %>% 
  write_csv("gravity.csv")
```

## Safety check

```{r}
# Extract partners names
names <- gravity %>% distinct(iso_j) %>% as.list()
countries <- names$iso_j

# How many observations are there per partner?
rows <- tibble(countries = countries)

for(i in countries) {
  rows[[i]] <- gravity %>% filter(iso_j == i) %>% nrow()
}

rows %<>% 
  slice(1) %>% 
  pivot_longer(cols = (2:length(rows))) %>% 
  select(-countries)

# Pull only the partners with complete observations
complete <- rows %>% filter(value == 26) %>% pull(1)

setequal(countries, complete)
```

```{r}
# Gravity db with only complete partners
gravity %<>% filter(partner_iso %in% complete)

# How many partners does the db have?
gravity %>% distinct(partner_iso) %>% dim()
```

## 2 --- Badly specified gravity model estimation

```{r}
pacman::p_load(panelr, plm, broom)
```

$$
X_{ij}=G\frac{Y_{i}^{\beta_{1}}Y_{j}^{\beta_{2}}}{t_{ij}^{\beta_{3}}}.
$$

```{r}
panel <- panel_data(gravity %>% filter(trade_value > 0), id = partner_iso, wave = year)
```

```{r}
fit <- plm(log(trade_value) ~ log(i_gdp) + log(j_gdp) + log(dist),
           data = panel,
           index = c("partner_iso", "year"),
           model = "pooling")

summary(fit)
```
