# Econometric estimation

```{r include=FALSE}
pacman::p_load(tidyverse, gravity, here, panelr, plm, broom, pglm, geepack)
```

```{r include=FALSE}
gravity <- read_csv("gravity.csv")
```

## Traditional gravity equation

$$
F_{ij}=G\frac{Y_{i}^{\beta_{1}}Y_{j}^{\beta_{2}}}{d_{ij}^{\beta_{3}}}.
$$

```{r include=FALSE}
exports <- panel_data(gravity %>% filter(exports > 0), id = iso_j, wave = year)
imports <- panel_data(gravity %>% filter(imports > 0), id = iso_j, wave = year)
```

```{r echo=FALSE}
exports_fit <- plm(log(exports) ~ log(gdp_pcap_i) + log(gdp_pcap_j) + log(dist),
                   data = exports,
                   index = c("iso_j", "year"),
                   model = "pooling")

summary(exports_fit)
```

```{r echo=FALSE}
imports_fit <- plm(log(imports) ~ log(gdp_pcap_i) + log(gdp_pcap_j) + log(dist),
                   data = imports,
                   index = c("iso_j", "year"),
                   model = "pooling")

summary(imports_fit)
```

## Poisson Pseudo Maximum Likelihood

```{r}
gravity_test <- 
  gravity |> 
  mutate(imports = log(imports),
         gdp_pcap_i = log(gdp_pcap_i),
         gdp_pcap_j = log(gdp_pcap_j),
         distance = log(dist)) |> 
  filter(imports > 0 | gdp_pcap_i > 0 | gdp_pcap_j > 0 | distance > 0)


model_ppml <- 
  glm(formula = imports ~ gdp_pcap_i + gdp_pcap_j + distance, 
      family = quasipoisson(link = "log"),
      data = gravity_test)

robust_coefficients <- lmtest::coeftest(model_ppml, 
                                        vcov = sandwich::vcovHC(model_ppml, 
                                                                type = "HC1"))

model_ppml$coefficients <- 
  robust_coefficients[1:length(rownames(robust_coefficients))]

model_ppml |> 
  summary()
```

```{r}
pglm(formula = imports ~ gdp_pcap_i + gdp_pcap_j + distance,
     effect = "individual",
     model = "pooling",
     family = poisson(link = "log"),
     data = gravity_test,
     index = "year") |> 
  summary()
```
