---
output:
  pdf_document:
    latex_engine: xelatex
mainfont: Helvetica Neue
geometry: "left = 2.5cm, right = 2.5cm, top = 2.5cm, bottom = 2.5cm"
fontsize: 11pt
header-includes: 
  - \usepackage{setspace}\spacing{1} 
  - \pagenumbering{gobble}
---

# Econometric estimation

```{r, include=FALSE}
pacman::p_load(
  tidyverse, here, broom, gravity, panelr, plm, nlme, lmtest, stargazer, fixest, kableExtra
  )
```

```{r, include=FALSE}
gravity_raw <- 
  read_csv(here("gravity.csv"))

exports <- 
  gravity_raw |> 
  rename(iso_o = iso_i, iso_d = iso_j, trade = exports) |> 
  select(!imports) |> 
  mutate(trade_log = log(trade + 1)) |> 
  panel_data(id = iso_d, wave = year)

imports <- 
  gravity_raw |> 
  rename(iso_d = iso_i, iso_o = iso_j, trade = imports) |> 
  select(!exports) |> 
  mutate(trade_log = log(trade + 1)) |> 
  panel_data(id = iso_o, wave = year)
```

```{r, include=FALSE}
formula_ols <- 
  trade_log ~ tgdp + rfe + sim + log(dist) + cont + lang + ccol + crel + rta

formula_poisson <- 
  trade ~ tgdp + rfe + sim + log(dist) + cont + lang + ccol + crel + rta
```

#### Pooled estimator

```{r, include=FALSE}
exports_pols <- 
  plm(formula_ols,
      data = exports,
      model = 'pooling',
      index = c('iso_d'))

imports_pols <- 
  plm(formula_ols,
      data = imports,
      model = 'pooling',
      index = c('iso_o'))
```

#### Random effects estimator

```{r, include=FALSE}
exports_ree <- 
  plm(formula_ols,
      data = exports,
      index = c('iso_d'),
      model = 'random',
      effect = 'individual')

imports_ree <- 
  plm(formula_ols,
      data = imports,
      index = c('iso_o'),
      model = 'random',
      effect = 'individual')
```

#### Fixed effects estimator

```{r, include=FALSE}
exports_fee <- 
  plm(formula_ols,
      data = exports,
      index = c('iso_d'),
      model = 'within',
      effect = 'individual')

imports_fee <- 
  plm(formula_ols,
      data = imports,
      index = c('iso_o'),
      model = 'within',
      effect = 'individual')
```

#### Poisson pseudo-maximum-likelihood estimator

For regressors not in logs, the semi-elasticity is given by 100\*(exp(beta) - 1)%.

<https://www.statalist.org/forums/forum/general-stata-discussion/general/1458657-interpretation-of-coefficients-in-gravity-model-using-ppml-dummies>

```{r, include=FALSE}
poisson_int <- 
  ppml(
  dependent_variable = 'trade',
  distance = 'dist',
  additional_regressors = c('tgdp', 'rfe', 'sim', 'cont', 'lang', 'ccol', 'crel', 'rta'),
  robust = FALSE,
  data = exports
)

poisson_int |> summary()
```

```{r, include=FALSE}
exports_ppml <- 
  glm(formula_poisson,
      family = quasipoisson(link = "log"),
      data = exports)

# exports_pseudo_rsqr <- 1 - ((exports_ppml$deviance) / exports_ppml$null.deviance)

imports_ppml <- 
  glm(formula_poisson,
      family = quasipoisson(link = "log"),
      data = imports)

# imports_pseudo_rsqr <- 1 - ((imports_ppml$deviance)/ imports_ppml$null.deviance)
```

### Results

```{r, include=FALSE}
vars <- c("Suma bilateral del producto interno bruto",
          "Diferencia en la dotación relativa de factores",
          "Similitud en el tamaño de las economías",
          "Distancia entre principales centros urbanos",
          "Fronteras en común",
          "Lenguaje en común", 
          "Colonizador en común",
          "Índice de similitud en creencias religiosas",
          "Acuerdos comerciales regionales",
          "Constante")
```

```{r, include=FALSE}
exports_rob_se <- list(sqrt(diag(vcovHC(exports_pols, type = "HC1"))),
                       sqrt(diag(vcovHC(exports_ree, type = "HC1"))),
                       sqrt(diag(vcovHC(exports_fee, type = "HC1"))),
                       sqrt(diag(vcovHC(exports_ppml, type = "HC1"))))

imports_rob_se <- list(sqrt(diag(vcovHC(imports_pols, type = "HC1"))),
                       sqrt(diag(vcovHC(imports_ree, type = "HC1"))),
                       sqrt(diag(vcovHC(imports_fee, type = "HC1"))),
                       sqrt(diag(vcovHC(imports_ppml, type = "HC1"))))
```

```{r, results='asis', echo=FALSE}
stargazer(exports_pols, exports_ree, exports_fee, exports_ppml,
          column.labels = c("POLS", "REE", "FEE", "PPML"),
          se = exports_rob_se,
          covariate.labels = vars,
          dep.var.caption = "",
          dep.var.labels.include = FALSE,
          model.names = FALSE,
          model.numbers = TRUE,
          column.sep.width = "-5pt",
          font.size = "small",
          style = "qje",
          table.layout = "-c-#-t-sa-n",
          df = FALSE,
          # add.lines = list(c('Pseudo R$^2$', '', '', '', round(exports_pseudo_rsqr, 3))),
          notes.append = FALSE)
```

```{r, results='asis', echo=FALSE}
stargazer(imports_pols, imports_ree, imports_fee, imports_ppml,
          column.labels = c("POLS", "REE", "FEE", "PPML"),
          se = imports_rob_se,
          covariate.labels = vars,
          dep.var.caption = "",
          dep.var.labels.include = FALSE,
          model.names = FALSE,
          model.numbers = TRUE,
          column.sep.width = "-5pt",
          font.size = "small",
          style = "qje",
          table.layout = "-c-#-t-sa-n",
          df = FALSE,
          # add.lines = list(c('Pseudo R$^2$', '', '', '', round(imports_pseudo_rsqr, 3))),
          notes.append = FALSE)
```

#### Tests

```{r, results='asis', echo=FALSE}
bptest(exports_pols) |>
  glance() |>
  select(
    Estadístico = statistic,
    `Valor p` = p.value,
    `Grados de libertad` = parameter
  ) |>
  mutate(Modelo = 'POLS (Exportaciones)') |>
  relocate(Modelo) |>
  bind_rows(
    bptest(imports_pols) |>
      glance() |>
      select(
        Estadístico = statistic,
        `Valor p` = p.value,
        `Grados de libertad` = parameter
        ) |>
      mutate(Modelo = 'POLS (Importaciones)') |>
      relocate(Modelo)
  ) |>
  bind_rows(
    plm::phtest(exports_ree, exports_fee, effect = 'individual') |>
      glance() |>
      select(
        Estadístico = statistic,
        `Valor p` = p.value,
        `Grados de libertad` = parameter
      ) |>
      mutate(Modelo = 'REE & FEE (Exportaciones)') |>
      relocate(Modelo) |>
      bind_rows(
        plm::phtest(imports_ree, imports_fee, effect = 'individual') |>
          glance() |>
          select(
            Estadístico = statistic,
            `Valor p` = p.value,
            `Grados de libertad` = parameter
          ) |>
          mutate(Modelo = 'REE & FEE (Importaciones)') |>
          relocate(Modelo)
      )
  ) |> 
kable(
  booktabs = TRUE,
  align = c('cccc'),
  format.args = list(big.mark = ","),
  linesep = ""
) |>
  pack_rows(
    'Breusch-Pagan test',
    1,
    2,
    latex_gap_space = "0.5em",
    bold = FALSE,
    italic = TRUE
  ) |>
  pack_rows(
    'Hausman test',
    3,
    4,
    latex_gap_space = "0.5em",
    bold = FALSE,
    italic = TRUE
  ) |>
  kable_styling()
```

#### RESET test

```{r, include=FALSE}
resettest(formula_poisson, power = 2, type = 'regressor', data = exports)
resettest(formula_poisson, power = 2, type = 'regressor', data = imports)
```
