# Coefficients evolution over time

```{r}
pacman::p_load(tidyverse, broom, here, janitor, panelr, plm, lmtest, patchwork)
```

```{r}
gravity_raw <- 
  read_csv(here("gravity.csv"))

exports_data <- 
  gravity_raw |> 
  rename(iso_o = iso_i, iso_d = iso_j, trade = exports) |> 
  select(!imports) |> 
  mutate(trade_log = log(trade + 1)) |> 
  panel_data(id = iso_d, wave = year)

imports_data <- 
  gravity_raw |> 
  rename(iso_d = iso_i, iso_o = iso_j, trade = imports) |> 
  select(!exports) |> 
  mutate(trade_log = log(trade + 1)) |> 
  panel_data(id = iso_o, wave = year)

formula <- 
  trade ~ tgdp + rfe + sim + log(dist) + cont + lang + ccol + crel + rta
```

```{r}
extract <- function(data, formula, date) {
  filtered_data <- data |> filter(year == date)
  
  model <-
    glm(formula,
        family = quasipoisson(link = "log"),
        data = filtered_data)
  
  tidy <- model |> tidy() |> mutate(year = date) |> relocate(year) |> select(!4:6)
  
  std <- 
    coeftest(model, vcov = vcovHC, type = "HC1", cluster = "group")[, 2] |> 
    as_tibble() |> 
    rename(std.error = value)
  
  result <- tidy |> bind_cols(std)
  return(result)
}
```

```{r}
dates <- c(1995:2020)
exports <- tibble()

for (date in dates) {
  extraction <- extract(exports_data, formula, date)
  exports <- bind_rows(exports, extraction)
}

imports <- tibble()

for (date in dates) {
  extraction <- extract(imports_data, formula, date)
  imports <- bind_rows(imports, extraction)
}
```

```{r}
exports |> 
  mutate(flow = 'Exportaciones') |> 
  bind_rows(imports |> mutate(flow = 'Importaciones')) |> 
  filter(term == 'rfe') |> 
  ggplot(aes(year, estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error),
                    alpha = .25) +
  geom_smooth(color = "#4E74BF", fill = "#4E74BF", alpha = .1,
                method = lm, se = FALSE, formula = y ~ splines::bs(x, 15)) +
  facet_wrap(~flow) +
  theme(
    text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
    axis.title = element_blank(),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = "none",
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(color = "gray15", size = 0.25),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(.5,0.1,.5,0.1), "cm")
    )
```

```{r}
ggsave(here("Econometrics", "Results", "RFE over time.png"), 
       width = 13, height = 6, dpi = 300, units = "in")
```

```{r}
spline_plot <- function(data, spline) {
  data |> 
    filter(term %in% c("rfe", "sim")) |> 
    ggplot(aes(year, estimate, color = term)) +
    geom_point(color = "gray15") +
    facet_wrap(vars(term), scales = "free") +
    geom_smooth(color = "#4E74BF", fill = "#4E74BF", alpha = .1,
                method = lm, formula = y ~ splines::bs(x, spline)) +
    scale_y_continuous() +
    theme(
      text = element_text(color = "gray15", 
                          family = "Helvetica Neue",
                          size = 19),
      axis.title = element_blank(),
      axis.text = element_text(color = "gray15"),
      axis.ticks = element_blank(),
      legend.title = element_blank(),
      legend.position = "none",
      legend.key = element_rect(fill = "white"),
      legend.background = element_rect(color = "gray15", size = 0.25),
      panel.background = element_rect(color = "gray15", fill = "white"),
      panel.grid = element_blank(),
      strip.background = element_rect(color = "gray15", fill = "gray15"),
      strip.text = element_text(color = "white"),
      plot.margin = unit(c(.5,0.1,.5,0.1), "cm"))
}
```

```{r}
exports |> spline_plot(15)
```

```{r}
ggsave(here("Econometrics", "Results", "RFE and SIM over time (exports).png"), 
       width = 13, height = 6, dpi = 300, units = "in")
```

```{r}
imports |> spline_plot(15)
```

```{r}
ggsave(here("Econometrics", "Results", "RFE and SIM over time (imports).png"), 
       width = 13, height = 6, dpi = 300, units = "in")
```
