# Coefficients evolution over time

```{r}
pacman::p_load(tidyverse, broom, here, janitor, panelr, plm, lmtest, patchwork)
gravity <- read_csv("gravity.csv")
```

```{r}
# Feature engineering
exports_data <- 
  gravity |> 
  mutate(exports = ifelse(log(exports) <= 0, 0, log(exports))) |> 
  panel_data(id = iso_j, wave = year)

imports_data <- 
  gravity |> 
  mutate(imports = ifelse(log(imports) <= 0, 0, log(imports))) |> 
  panel_data(id = iso_j, wave = year)
```

```{r}
# Declaring formulas
exports_formula <- 
  exports ~ tgdp + rfe + sim + log(dist) + log(rer) + cont + lang + 
  ccol + crel + rta

imports_formula <- 
  imports ~ tgdp + rfe + sim + log(dist) + log(rer) + cont + lang + 
  ccol + crel + rta
```

```{r}
extract <- function(data, formula, date) {
  filtered_data <- data |> filter(year == date)
  
  model <-
    glm(formula,
        family = quasipoisson(link = "log"),
        data = filtered_data)
  
  tidy <- model |> tidy() |> mutate(year = date) |> relocate(year) |> select(!4:6)
  
  std <- 
    coeftest(model, vcov = vcovHC, type = "HC1", cluster = "group")[, 2] |> 
    as_tibble() |> 
    rename(std.error = value)
  
  result <- tidy |> bind_cols(std)
  return(result)
}
```

```{r}
dates <- c(1995:2020)

exports <- tibble()

for (date in dates) {
  extraction <- extract(exports_data, exports_formula, date)
  exports <- bind_rows(exports, extraction)
}

imports <- tibble()

for (date in dates) {
  extraction <- extract(imports_data, imports_formula, date)
  imports <- bind_rows(imports, extraction)
}
```

```{r}
spline_plot <- function(data, term, spline, name) {
 data |> 
  filter(term == !!term) |> 
  ggplot(aes(year, estimate)) +
  geom_point() +
  geom_smooth(color = 2, fill = 2, alpha = .1,
              method = lm, formula = y ~ splines::bs(x, spline)) +
  ggtitle(paste0(name)) +
  theme(
    axis.title = element_blank(),
    axis.text = element_text(color = "black"),
    legend.key.height = unit(6.9, "line"),
    panel.background = element_rect(color = "gray10", fill = "white"),
    plot.background = element_rect(color= "white", fill = "white"),
    panel.grid = element_blank()
  )
}
```

```{r}
p1 <- spline_plot(exports, "rfe", 3, "RFE en exportaciones a lo largo del tiempo")
p2 <- spline_plot(exports, "sim", 3, "SIM en exportaciones a lo largo del tiempo")
p1 + p2
```

```{r}
ggsave(here("Econometrics", "Results", "RFE and SIM (exports).png"), 
       width = 12.5, height = 6, dpi = 300, units = "in")
```

```{r}
p3 <- spline_plot(imports, "rfe", 3, "RFE en importaciones a lo largo del tiempo")
p4 <- spline_plot(imports, "sim", 3, "SIM en importaciones a lo largo del tiempo")
p3 + p4
```

```{r}
ggsave(here("Econometrics", "Results", "RFE and SIM (imports).png"), 
       width = 12.5, height = 6, dpi = 300, units = "in")
```
