# Descriptive statistics

```{r}
pacman::p_load(tidyverse, here)
```

#### Gravity dataset

```{r}
gravity <- 
  read_csv(here("gravity.csv")) |> 
  mutate(exports = ifelse(log(exports) <= 0, 0, log(exports)),
         imports = ifelse(log(imports) <= 0, 0, log(imports)),
         dist = log(dist)) |> 
  select(where(is.numeric))
```

#### Descriptive statistics table

```{r}
gravity_longer <- 
  gravity |> 
  pivot_longer(!year, names_to = "Variable", values_to = "value")  |> 
  mutate(Variable = fct_relevel(factor(Variable),
                                "exports", "imports", "tgdp", "rfe",
                                "sim", "dist", "cont", "lang", "ccol", 
                                "crel", "rta")) |> 
  arrange(Variable, year) |> 
  group_by(Variable)

descriptive <- 
  gravity_longer |> 
  summarise(Media = round(mean(value), 2),
            Mediana = round(median(value), 2),
            Mínimo = round(min(value), 2),
            Máximo = round(max(value), 2),
            `Desv. Est.` = round(sd(value), 2),
            Asimetría = round(e1071::skewness(value), 2),
            Curtosis = round(e1071::kurtosis(value), 2))

obs <- 
  gravity_longer |> 
  count(Variable) |> 
  rename(`Obs.` = n)

descriptive_stats <- 
  descriptive |> 
  left_join(obs) |> 
  as.data.frame()
```

```{r}
descriptive_stats |> 
  write_csv(here("Data visualization", "Tables", "descriptive_stats.csv"))
```

#### Histograms

```{r}
gravity_longer |> 
  ggplot(aes(value)) +
  geom_histogram(aes(y = ..density..),
                 color = 1, fill = "white",
                 lwd = .25, bins = 50) +
  geom_density(lwd = .45, color = "#D94343",
               fill = "#D94343", alpha = .25) +
  facet_wrap(~Variable, scales = "free") +
  theme(
    text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
    axis.title = element_blank(),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.82, .92),
    legend.direction = "horizontal", 
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(color = "gray15", size = 0.25),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(.5,0.1,.5,0.1), "cm")
  )
```

```{r}
ggsave(here("Data visualization", "Plots", "histograms.png"), 
       width = 13, height = 7, dpi = 300, units = "in")
```

#### Correlation matrix

```{r}
# Correlation matrix
gravity |> 
  select(where(is.numeric)) |> 
  cor() |> 
  ggcorrplot::ggcorrplot(show.diag = FALSE,
                         outline.color = FALSE,
                         lab = TRUE,
                         type = "lower",
                         color = c("#4E74BF", "#F2EFE4", "#D94343"))  +
  theme(
    axis.text = element_text(color = "black"),
    legend.key.height = unit(6.9, "line"),
    legend.title = element_blank(),
    panel.background = element_rect(color = "gray10", fill = "white"),
    plot.background = element_rect(color= "white", fill = "white"),
    panel.grid = element_blank()
  )
```

```{r}
ggsave(here("Data visualization", "Plots", "correlation matrix.png"), 
       width = 8.5, height = 8.5, dpi = 300, units = "in")
```
