# Trade intensity maps

```{r}
pacman::p_load(tidyverse, here, sf, patchwork)
```

### Export/Import map

```{r}
gravity <- read_csv(here("gravity.csv"))|> 
  mutate(exports = ifelse(log(exports) <= 0, 0, log(exports)),
         imports = ifelse(log(imports) <= 0, 0, log(imports)))

codes <- read_csv("https://git.io/v564u") |> select(country = name, iso_j = `alpha-3`)
mapdata <- map_data("world") %>% as_tibble() |> rename(country = region)
```

```{r}
gravity_map <- 
  gravity |> 
  group_by(iso_j) |> 
  mutate(exports = mean(exports),
         imports = mean(imports)) |> 
  filter(year == 2020) |> 
  select(iso_j, exports, imports) |> 
  left_join(codes) |> 
  relocate(country) |> 
  rename(iso = iso_j) |> 
  ungroup() |> 
  mutate(country = case_when(
    country == "United States of America" ~ "USA",
    country == "Bolivia (Plurinational State of)" ~ "Bolivia",
    country == "Trinidad and Tobago" ~ "Trinidad",
    country == "Saint Vincent and the Grenadines" ~ "Saint Vincent",
    TRUE ~ country
  )) |> 
  right_join(mapdata)
```

```{r}
map_aesthetics <- function(val, ...) {
    theme(
      plot.title = element_text(size = 20),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      legend.position = "bottom",
      legend.key.width = unit(val, "line"),
      legend.title = element_blank(),
      panel.background = element_rect(fill = "gray95"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()
    )
}
```

```{r}
p1 <- 
  gravity_map |> 
  ggplot(aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = exports), color = "white", size = .1) +
  coord_cartesian(xlim = c(-170, -35), ylim = c(-55, 82)) +
  scale_fill_gradientn(colours = c("#4E74BF", "#F2EFE4", "#D94343"),
                     values = scales::rescale(c(-0.1, -0.05, 0, 0.05, 0.1)),
                     na.value = "gray30") +
  map_aesthetics(val = 7.6) +
  theme(text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
        plot.margin = unit(c(.5,0.1,.5,0.1), "cm"))

p2 <- 
  gravity_map |> 
  ggplot(aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = imports), color = "white", size = .1) +
  coord_cartesian(xlim = c(-170, -35), ylim = c(-55, 82)) +
  scale_fill_gradientn(colours = c("#4E74BF", "#F2EFE4", "#D94343"),
                     values = scales::rescale(c(-0.1, -0.05, 0, 0.05, 0.1)),
                     na.value = "gray30") +
  map_aesthetics(val = 7.6) +
  theme(text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
        plot.margin = unit(c(.5,0.1,.5,0.1), "cm"))

p1 + p2
```

```{r}
ggsave(here("Data visualization", "Plots", "maps.png"), 
       width = 16, height = 9, dpi = 300, units = "in")
```
