# Commercial balance analysis

```{r}
pacman::p_load(tidyverse, here, comtradr, patchwork)
```

```{r}
total_raw <- 
  ct_search(
    reporters = "Guatemala",
    partners = "World",
    trade_direction = "all",
    freq = "annual",
    commod_codes = "TOTAL",
    type = "goods"
    )

total <- 
  total_raw |> 
  as_tibble() |> 
  arrange(year) |> 
  select(year, trade_flow, trade_value_usd) |> 
  pivot_wider(names_from = trade_flow, values_from = trade_value_usd) |> 
  select(!4) |> 
  rename(imports_total = Import, exports_total = Export) |> 
  filter(between(year, 1995, 2020)) |> 
  relocate(year, exports_total)

gravity <- 
  read_csv(here("gravity.csv")) |> 
  select(year, iso_j, exports, imports) |> 
  group_by(year) |> 
  summarise(exports = sum(exports),
            imports = sum(imports))

balance_raw <- 
  total |> 
  left_join(gravity) |> 
  mutate(balance_total = exports_total - imports_total,
         balance = exports - imports,
         across(2:7, ~ .x / 1e6))
```

```{r}
balance <- 
  balance_raw |> 
  pivot_longer(!year) |> 
  mutate(id = ifelse(str_detect(name, "_total"), "Mundo", "América")) |> 
  pivot_wider(names_from = name, values_from = value) |> 
  mutate(id = fct_relevel(id, "Mundo", "América"),
         across(where(is.numeric), ~ replace_na(., 0)),
         Exportaciones = exports_total + exports,
         `Importaciones   ` = imports_total + imports,
         balance = balance_total + balance) |> 
  select(year, id, Exportaciones, `Importaciones   `, balance) |> 
  pivot_longer(!c(year, id), names_to = "flow") |> 
  group_by(year, id) |> 
  mutate(balance = value[flow == "balance"]) |> 
  filter(flow != "balance") |> 
  mutate(balance = balance / 2)
```

```{r}
balance |> 
  ggplot(aes(year)) +
  
  # World
  geom_line(aes(y = value, color = flow),
            data = balance |> filter(id == "Mundo")) +
  geom_point(aes(y = value, color = flow),
            data = balance |> filter(id == "Mundo")) +
  geom_col(aes(y = balance),
           data = balance |> filter(id == "Mundo"),
           fill = "gray15") +
  
  # America
  geom_line(aes(y = value, color = flow),
            data = balance |> filter(id == "América")) +
  geom_point(aes(y = value, color = flow),
            data = balance |> filter(id == "América")) +
  geom_col(aes(y = balance),
           data = balance |> filter(id == "América"),
           fill = "gray15") +
  
  facet_wrap(vars(id))  +
  scale_y_continuous(breaks = seq(-10000, 20000, by = 2000),
                     label = scales::comma) +
  scale_x_continuous(breaks = seq(1995, 2020, by = 5)) +
  scale_color_manual(values = c("#91C4D9", 2)) +
  
  theme(
    text = element_text(color = "gray15"),
    axis.title = element_blank(),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.14, .92),
    legend.direction = "horizontal", 
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(color = "gray15", size = 0.25),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(1,1,1,1), "cm")
  )
```

```{r}
ggsave(here("Data visualization", "Plots", "trade balance.png"), 
       width = 13, height = 7, dpi = 300, units = "in")
```
