# Share of trade flows

```{r}
pacman::p_load(tidyverse, here, comtradr, ggstream)
gravity <- read_csv(here("gravity.csv")) |> select(year, iso_j, exports, imports)
```

#### Extraction from UN Comtrade API

```{r}
query <- function(year) {
  ct_search(
    reporters = "Guatemala",
    partners = "World",
    trade_direction = "all",
    start_date = year,
    end_date = year,
    freq = "annual",
    commod_codes = "TOTAL",
    type = "goods"
    ) |> 
    as_tibble() |> 
    select(year, trade_flow, trade_value_usd) |> 
    mutate(trade_flow = as.character(trade_flow))
}

years <- c(1995:2020)
total_raw <- tibble()

for (year in years) {
  extraction <- query(year)
  total_raw <- bind_rows(total_raw, extraction)
}
```

#### Data wringling

```{r}
total <- 
  total_raw |>
  filter(trade_flow != "Re-Import") |> 
  arrange(year) |> 
  pivot_wider(names_from = trade_flow, values_from = trade_value_usd) |> 
  rename(imports_total = Import, exports_total = Export) |> 
  filter(between(year, 1995, 2020)) |> 
  relocate(year, exports_total)

 america <- 
  gravity |> 
  group_by(year) |> 
  # filter(iso_j != "USA") |> 
  summarise(exports_america = sum(exports),
            imports_america = sum(imports))

usa <- 
  gravity |> 
  group_by(year) |> 
  filter(iso_j == "USA") |> 
  summarise(exports_usa = sum(exports),
            imports_usa = sum(imports))
```

```{r}
flows <- 
  total |> 
  left_join(america) |> 
  left_join(usa) |> 
  mutate(across(2:7, ~ .x / 1e6),
         exports_total = exports_total - exports_america,
         exports_america = exports_america - exports_usa,
         imports_total = imports_total - imports_america,
         imports_america = imports_america - imports_usa) |> 
  pivot_longer(!year) |> 
  mutate(id = ifelse(str_detect(name, "exports"), "Exportaciones", "Importaciones"),
         name = case_when(
           str_detect(name, "_total") ~ "Total",
           str_detect(name, "_america") ~ "América",
           str_detect(name, "_usa") ~ "Estados Unidos  "
         )) |> 
  relocate(year, id) |> 
  mutate(name = fct_relevel(name, "Total", "América", "Estados Unidos  "))
```

#### Data visualization

```{r}
flows |> 
  ggplot(aes(year, value, fill = name)) +
  geom_area() +
  facet_wrap(vars(id)) +
  scale_y_continuous(breaks = seq(-10000, 20000, by = 2000),
                     label = scales::comma) +
  scale_x_continuous(breaks = seq(1995, 2020, by = 5)) +
  scale_fill_manual(values = c("#4E74BF", "#F2EFE4", "#D94343"))  +
  theme(
    text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
    axis.title = element_blank(),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.205, .92),
    legend.direction = "horizontal", 
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(color = "gray15", size = 0.25),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(.5,0.1,.5,0.1), "cm")
  )
```

```{r}
ggsave(here("Data visualization", "Plots", "share of trade flows.png"), 
       width = 13, height = 6, dpi = 300, units = "in")
```

#### Proportions over time

```{r}
flows <- 
  flows |> 
  mutate(name = str_to_lower(str_trim(name))) |> 
  pivot_wider(names_from = name, values_from = value) |> 
  janitor::clean_names() |> 
  mutate(america = america + estados_unidos,
         total = total + america)
```

```{r}
exports_us <- 
  flows |> 
  filter(id == 'Exportaciones') |> 
  mutate(`Exp.` = estados_unidos/total) |> 
  select(!c(id, total, america, estados_unidos))
  
imports_us <- 
  flows |> 
  filter(id == 'Importaciones') |> 
  mutate(`Imp.   ` = estados_unidos/total) |> 
  select(!c(year, id, total, america, estados_unidos))

prop_us <- exports_us |> bind_cols(imports_us)
```

```{r}
exports_am <- 
  flows |> 
  filter(id == 'Exportaciones') |> 
  mutate(`Exp.` = america/total) |> 
  select(!c(id, total, america, estados_unidos))
  
imports_am <- 
  flows |> 
  filter(id == 'Importaciones') |> 
  mutate(`Imp.   ` = america/total) |> 
  select(!c(year, id, total, america, estados_unidos))

prop_am <- exports_am |> bind_cols(imports_am)
```

```{r}
library(patchwork)

p1 <- 
  prop_am |> 
  pivot_longer(!year, names_to = 'flows') |> 
  ggplot(aes(year, value, color = flows)) +
  geom_line() +
  geom_point() +
  ggtitle('América') +
  scale_color_manual(values = c("#4E74BF", "#D94343"))  +
  theme(
    title = element_text(size = 15),
    text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
    axis.title = element_blank(),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = 'none',
    legend.direction = "horizontal", 
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(color = "gray15", size = 0.25),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(.5,0.1,.5,0.1), "cm")
  )

p2 <- 
  prop_us |> 
  pivot_longer(!year, names_to = 'flows') |> 
  ggplot(aes(year, value, color = flows)) +
  geom_line() +
  geom_point() +
  ggtitle('Estados Unidos') +
  scale_color_manual(values = c("#4E74BF", "#D94343"))  +
  theme(
    title = element_text(size = 15),
    text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
    axis.title = element_blank(),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = c(.785, .92),
    legend.direction = "horizontal", 
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(color = "gray15", size = 0.25),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(.5,0.1,.5,0.1), "cm")
  )

p1 + p2
```

```{r}
ggsave(here("Data visualization", "Plots", "shares of trade over time.png"), 
       width = 13, height = 6, dpi = 300, units = "in")
```
