# Trade openness

```{r}
pacman::p_load(tidyverse, here, WDI, sysfonts)

gravity <- read_csv(here("gravity.csv")) |> select(year, iso_j, exports, imports)

countries <- 
  read_csv(here("Data", "Main data frames", "partners_names.csv")) |> 
  pull(partner_iso) |> 
  append("GTM")
```

#### Trade openness over time

```{r}
query <- function(country) {
  WDI(
    indicator = c(openness = "NE.TRD.GNFS.ZS"),
    country = country,
    start = 1995,
    end = 2020
  ) |> 
    as_tibble()
}

openness <- tibble()

for (country in countries) {
  data <- query(country)
  openness <- bind_rows(openness, data)
}
```

```{r}
america <- 
  openness |> 
  select(!iso2c) |> 
  pivot_wider(names_from = country, values_from = openness) |>
  select_if(~ !any(is.na(.))) |> 
  pivot_longer(!year) |> 
  arrange(name, year) |> 
  group_by(year) |> 
  summarise(openness = mean(value)) |> 
  mutate(country = "América")

guatemala <- 
  openness |> 
  filter(country == "Guatemala") |> 
  select(!iso2c)

world <- 
  WDI(
    indicator = c(openness = "NE.TRD.GNFS.ZS"),
    country = "WLD",
    start = 1995,
    end = 2020
  ) |> 
    as_tibble() |> 
  select(!iso2c) |> 
  mutate(country = "Mundo")
```

```{r}
america |> 
  bind_rows(guatemala) |> 
  bind_rows(world) |> 
  ggplot(aes(year, openness, color = country)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_color_manual(values = c("#4E74BF", "#D94343", "gray50")) +
  theme(
    text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
    axis.title = element_blank(),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.18, .92),
    legend.direction = "horizontal", 
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(color = "gray15", size = 0.25),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(.5,0.1,.5,0.1), "cm")
  )
```

```{r}
ggsave(here("Data visualization", "Plots", "trade openness.png"), 
       width = 13, height = 6, dpi = 300, units = "in")
```
