# Appendix

```{r}
pacman::p_load(tidyverse, here)
```

#### Trade flows

```{r}
gravity <- 
  read_csv(here("gravity.csv")) |> 
  select(year, iso_j, exports, imports)
```

```{r}
gravity |> 
  pivot_longer(!c(year, iso_j), names_to = "flows", values_to = "value") |> 
  transmute(year, iso = factor(iso_j), flows = factor(flows), value) |> 
  filter(flows == "exports") |> 
  ggplot(aes(year, value)) +
  geom_col(fill = "gray30") +
  scale_y_continuous(labels = scales::scientific) +
  facet_wrap(~iso, scales = "free",
             nrow = 8, ncol = 4)  +
  theme(
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(.5,0.1,.5,0.1), "cm")
  )
```

```{r}
ggsave(here("Data visualization", "Plots", "exports.png"), 
       width = 8.5, height = 11, dpi = 300, units = "in")
```

```{r}
gravity |> 
  pivot_longer(!c(year, iso_j), names_to = "flows", values_to = "value") |> 
  transmute(year, iso = factor(iso_j), flows = factor(flows), value) |> 
  filter(flows == "imports") |> 
  ggplot(aes(year, value)) +
  geom_col(fill = "gray30") +
  scale_y_continuous(labels = scales::scientific) +
  facet_wrap(~iso, scales = "free",
             nrow = 8, ncol = 4)  +
  theme(
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(.5,0.1,.5,0.1), "cm")
  )
```

```{r}
ggsave(here("Data visualization", "Plots", "imports.png"), 
       width = 8.5, height = 11, dpi = 300, units = "in")
```
