# Grubel-Lloyd index

```{r}
pacman::p_load(tidyverse, here, patchwork, ggrepel)
```

```{r}
gravity <- read_csv(here("gravity.csv")) |> select(year, iso_j, rfe, sim)

trade_flows <- 
  read_csv(here("Data", "Main data frames", "trade_flows.csv")) |> 
  select(year, trade_flow, partner_iso, commodity, 
         commodity_code, value = trade_value_usd) |> 
  filter(partner_iso != "CUB")
```

#### Grubel-Lloyd index over time

$$
GL_i = \frac{(X_i + M_i) - |X_i - M_i|}{X_i + M_i} = 1 - \frac{|X_i - M_i|}{X_i + M_i}
$$

```{r}
gl <- 
  trade_flows |> 
  pivot_wider(names_from = trade_flow, values_from = value) |> 
  mutate(across(where(is.numeric), ~ replace_na(., 0))) |> 
  group_by(year, commodity, commodity_code) |> 
  summarise(export = sum(Export),
            import = sum(Import)) |> 
  mutate(index = 1 - (abs(export - import) / (export + import))) |> 
  select(year, commodity, commodity_code, index)
```

```{r}
p1 <- 
  gl |> 
  group_by(year) |> 
  summarise(index = mean(index)) |> 
  ggplot(aes(year, index)) +
  geom_line(color = 2) +
  ylim(0, .4) +
  theme(
    text = element_text(color = "gray15"),
    axis.title = element_blank(),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.15, .92),
    legend.direction = "horizontal", 
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(color = "gray15", size = 0.25),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(1,1,1,1), "cm")
  )
```

#### Grubel-Lloyd index over time by partner

```{r}
gl_partner_ts <- 
  trade_flows |> 
  pivot_wider(names_from = trade_flow, values_from = value) |> 
  mutate(across(where(is.numeric), ~ replace_na(., 0))) |> 
  group_by(year, partner_iso, commodity) |> 
  summarise(export = sum(Export),
            import = sum(Import)) |> 
  mutate(gl = 1 - (abs(export - import) / (export + import))) |> 
  select(year, partner_iso, commodity, gl) |> 
  group_by(partner_iso, year) |> 
  summarise(gl = mean(gl))
```

```{r}
gl_partner_ts |> 
  ggplot(aes(year, gl, fill = partner_iso)) +
  geom_line(color = "gray90") +
  geom_line(data = gl_partner_ts |> filter(partner_iso == "SLV"),
            aes(year, gl, color = "SLV")) +
  geom_line(data = gl_partner_ts |> filter(partner_iso == "USA"),
            aes(year, gl, color = "USA")) +
  geom_line(data = gl_partner_ts |> filter(partner_iso == "CRI"),
            aes(year, gl, color = "CRI")) +
  geom_line(data = gl_partner_ts |> filter(partner_iso == "HND"),
            aes(year, gl, color = "HND")) +
  geom_line(data = gl_partner_ts |> filter(partner_iso == "PAN"),
            aes(year, gl, color = "PAN")) +
  scale_color_manual(values=c("#4E74BF", "#3C5473", "#BAB1AC", "#D9958F", "#D94343")) +
  theme(
    text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
    axis.title = element_blank(),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.205, .92),
    legend.direction = "horizontal", 
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(color = "gray15", size = 0.25),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    plot.margin = unit(c(.5,0.1,.5,0.1), "cm")
  )
```

```{r}
ggsave(here("Data visualization", "Plots", "gl index over time.png"), 
       width = 13, height = 6, dpi = 300, units = "in")
```

#### GL index vs. RFE and SIM index

```{r}
gl_partner <- 
  trade_flows |> 
  pivot_wider(names_from = trade_flow, values_from = value) |> 
  mutate(across(where(is.numeric), ~ replace_na(., 0))) |> 
  group_by(year, partner_iso, commodity) |> 
  summarise(export = sum(Export),
            import = sum(Import)) |> 
  mutate(gl = 1 - (abs(export - import) / (export + import))) |> 
  select(year, partner_iso, commodity, gl) |> 
  group_by(partner_iso) |> 
  summarise(gl = mean(gl)) |> 
  rename(iso_j = partner_iso)

rfe_partner <- 
  gravity |> 
  group_by(iso_j) |> 
  summarise(rfe = mean(rfe))

sim_partner <- 
  gravity |> 
  group_by(iso_j) |> 
  summarise(sim = mean(sim))

index <- 
  gl_partner |> 
  left_join(rfe_partner) |> 
  left_join(sim_partner)
```

```{r}
geom_thesis <- 
  function(...){
    theme(
    text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
    plot.title = element_text(size = 18),
    axis.title.x = element_text(margin = margin(1, 0, 0, 0, unit = 'cm')),
    axis.title.y = element_text(margin = margin(0, 1, 0, 0, unit = 'cm')),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.205, .92),
    legend.direction = "horizontal", 
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(color = "gray15", size = 0.25),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(.5,0.1,.5,0.1), "cm")
  )
}
```

```{r}
p1 <- 
  index |> 
  ggplot(aes(rfe, gl)) +
  geom_smooth(method = lm, formula = y ~ splines::ns(x, 2), se = TRUE,
              color = "#4E74BF", fill = "#4E74BF", alpha = .1) +
  geom_point(position = position_jitter()) +
  geom_text_repel(aes(label = iso_j), nudge_y = .01, size = 5) +
  geom_thesis() +
  xlab('Dotación relativa de factores de producción') +
  ylab('Índice Grubel-Lloyd')

p2 <- 
  index |> 
  ggplot(aes(sim, gl)) +
  geom_smooth(method = lm, formula = y ~ splines::ns(x, 2), se = TRUE,
              color = "#4E74BF", fill = "#4E74BF", alpha = .1) +
  geom_point(position = position_jitter()) +
  geom_text_repel(aes(label = iso_j), nudge_y = .01, size = 5) +
  geom_thesis() +
  xlab('Similitud en el tamaño de las economías') +
  ylab('')

p1 + p2
```

```{r}
ggsave(here("Data visualization", "Plots", "gl, sim and rfe.png"), 
       width = 13, height = 8, dpi = 300, units = "in")
```
