# Principal component analysis

```{r}
pacman::p_load(tidyverse, tidymodels, here, factoextra, patchwork)
```

#### Import data

```{r}
flows <- 
  read_csv(here("Data", "Main data frames", "trade_flows.csv")) |> 
  select(year, trade_flow, partner_iso, commodity_code, commodity, trade_value_usd) |> 
  mutate(commodity_code = str_extract(commodity_code, "^\\d{2}")) |> 
  mutate(hs = case_when(
    between(commodity_code, 1, 5) ~ "Animales y productos derivados",
    between(commodity_code, 6, 15) ~ "Productos vegetales",
    between(commodity_code, 16, 24) ~ "Alimentos preparados",
    between(commodity_code, 25, 27) ~ "Productos minerales",
    between(commodity_code, 28, 38) ~ "Productos químicos",
    between(commodity_code, 39, 40) ~ "Plásticos y sus manufacturas",
    between(commodity_code, 41, 43) ~ "Cueros, pieles y sus manufacturas",
    between(commodity_code, 44, 49) ~ "Madera y productos derivados",
    between(commodity_code, 50, 63) ~ "Textiles y artículos derivados",
    between(commodity_code, 64, 67) ~ "Calzado, sombreros y sombrillas",
    between(commodity_code, 68, 71) ~ "Artículos de piedra, cerámica y vidrio",
    between(commodity_code, 72, 83) ~ "Metales y artículos derivados",
    between(commodity_code, 84, 85) ~ "Maquinaria y equipo eléctrico",
    between(commodity_code, 86, 89) ~ "Vehículos y equipo asociado",
    between(commodity_code, 90, 97) ~ "Artículos misceláneos manufacturados",
    TRUE ~ "No especificados"
  ))
```

#### Helper functions

```{r}
# Prepare data for PCA
clean_flows <- 
  function(data, flow){
  data <- 
    flows |> 
    filter(trade_flow == !!flow) |> 
    select(!c(commodity_code, commodity)) |> 
    group_by(partner_iso, hs) |> 
    summarise(mean = mean(trade_value_usd)) |> 
    pivot_wider(names_from = hs, values_from = mean) |> 
    mutate_all(~ replace(., is.na(.), 0))
  return(data)
  }

# Apply PCA and generate the biplot
biplot <- 
  function(data){
   biplot <- 
    fviz_pca_biplot(
      prcomp(
        data |> 
          column_to_rownames('partner_iso'), 
        center = TRUE, scale. = TRUE
        ), 
      col.var = "contrib",
      col.ind = "gray15",
      repel = TRUE,
      axes.linetype = "dotted")
   return(biplot)
  }

# Plot aesthetics
plot_aesthetics <- function(...){
    theme(
    title = element_text(size = 15),
    text = element_text(color = "gray15", 
                        family = "Helvetica Neue",
                        size = 19),
    axis.title.y = element_text(vjust = +5),
    axis.title.x = element_text(vjust = -5),
    axis.text = element_text(color = "gray15"),
    axis.ticks = element_blank(),
    legend.title = element_blank(),
    legend.position = "right",
    legend.key.width = unit(1, "line"),
    legend.key.height = unit(6, "line"),
    legend.direction = "vertical", 
    legend.key = element_rect(fill = "white"),
    legend.background = element_blank(),
    panel.background = element_rect(color = "gray15", fill = "white"),
    panel.grid = element_blank(),
    strip.background = element_rect(color = "gray15", fill = "gray15"),
    strip.text = element_text(color = "white"),
    plot.margin = unit(c(.5,0.1,1,1), "cm")
  )
}
```

#### Biplots

```{r}
high = "#4E74BF"
low = "gray70"

exports <- 
  biplot(clean_flows(flows, 'Export')) +
  ggtitle('Exportaciones') +
  xlab('Componente 1 (Varianza explicada: 55.3%)') +
  ylab('Componente 2 (Varianza explicada: 19%)') +
  scale_colour_gradient(high = high, low = low) +
  plot_aesthetics()

imports <- 
  biplot(clean_flows(flows, 'Import')) +
  ggtitle('Importaciones') +
  xlab('Componente 1 (Varianza explicada: 63.7%)') +
  ylab('Componente 2 (Varianza explicada: 11.7%)') +
  scale_colour_gradient(high = high, low = low) +
  plot_aesthetics()

exports / plot_spacer() / imports + plot_layout(heights = c(7, 1, 7))
```

```{r}
ggsave(here("Data visualization", "Plots", "exports pca.png"), 
       width = 13, height = 16, dpi = 300, units = "in")
```

#### The tidy way

```{r eval=FALSE, include=FALSE}
exports <- 
  flows |> 
  filter(trade_flow == 'Export') |> 
  select(!c(commodity_code, commodity)) |> 
  group_by(partner_iso, hs) |> 
  summarise(mean = mean(trade_value_usd)) |> 
  pivot_wider(names_from = hs, values_from = mean) |> 
  mutate_all(~ replace(., is.na(.), 0))

pca_exports <- 
  recipe(~., data = exports) |> 
  update_role(partner_iso, new_role = 'id') |> 
  step_normalize(all_predictors()) |> 
  step_pca(all_predictors())

prep_exports <- prep(pca_exports)
tidy_exports <- tidy(prep_exports, 2)

tidy_exports |> 
  filter(component %in% paste0('PC', 1:2)) |> 
  mutate(component = fct_inorder(component)) |> 
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)
```
