# Macro variables

Basic specifications:

$$
\begin{align*}
ln F_{ij} &= c + \alpha ln (Y_i + Y_j) - \beta ln D_{ij} + \epsilon_{ij} \\
ln F_{ij} &= c + \alpha ln (Y_i^{pc} + Y_j^{pc}) - \beta ln D_{ij} + \epsilon_{ij} \\
ln F_{ij}^{manuf} &= c + \alpha ln |Y_i^{pc} - Y_j^{pc}| - \beta ln D_{ij} + \epsilon_{ij}
\end{align*}
$$

Where $(Y)$ denotes the gross domestic product, $Y^{pc}$ is the output per capita and $|Y_i^{pc} - Y_j^{pc}|$ represents the Linder variable.

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, here, WDI)
```

### Names query

```{r}
as_tibble(WDIsearch("exchange")) %>% print(n = Inf)
```

## (a) Extraction function

### Search parameters

```{r}
search <- function(country) {
  data <- WDI(
    indicator = c(
      gdp = "NY.GDP.MKTP.CD", # (current US$)
      gdp_pcap = "NY.GDP.PCAP.CD", # (current US$)
      population = "SP.POP.TOTL"
    ),
    country = country,
    start = 1995,
    end = 2020,
    extra = TRUE
  ) %>% 
    as_tibble()
}
```

### Export as .rds

```{r}
write <-
  function(data) {
    name <- deparse(substitute(data))
    write_csv(data, file = paste0(here("Data", "World Bank raw"), "/", name, ".csv"))
  }
```

## (b) Data extraction

### Countries in the main dataset

```{r}
partners <- 
  read_csv(here("Data", "Main data frames", "partners_names.csv")) %>% 
  pull(partner_iso)
```

### Extraction

```{r}
partners_wdi <- search(partners)
write(partners_wdi)
```

```{r}
guatemala_wdi <- search("GT")
write(guatemala_wdi)
```

## (c) Integrity check

### Guatemala macro data

```{r}
guatemala_wdi %>% 
  mutate(across(where(is.numeric), is.na)) %>% 
  select(where(is.logical)) %>% 
  summary()
```

### Commercial partners macro data

```{r}
# Extract partners names
names <- 
  partners_wdi %>% 
  distinct(iso2c) %>% 
  as.list()

countries <- names$iso2c

# How many observations are there per partner?
rows <- tibble(countries = countries)

for(i in countries) {
  rows[[i]] <- partners_wdi %>% filter(iso2c == i) %>% nrow()
}

rows %<>% 
  slice(1) %>% 
  pivot_longer(cols = (2:length(rows))) %>% 
  select(-countries)

# Pull only the partners with complete observations
complete <- rows %>% filter(value == 26) %>% pull(1)

# Are we good?
summary(partners_wdi)
summary(countries)
summary(complete)

# Yes we are
```
