# Trade flows data cleansing

```{r}
pacman::p_load(tidyverse, magrittr, here, comtradr)
```

```{r}
trade_flows <- read_csv(here("Data", "Main data frames", "trade_flows.csv"))
transaction_costs <- read_csv(here("Data", "Main data frames", "transaction_costs.csv"))
```

```{r}
exports_total <- 
  trade_flows %>% 
  filter(trade_flow == "Export") %>% 
  group_by(year, reporter_iso, partner_iso) %>% 
  summarise(trade_value = sum(trade_value_usd)) %>% 
  ungroup()
```

```{r}
# These are the countries and years for which we don't have trade flows
transaction_costs %>% 
  anti_join(exports_total) %>% 
  distinct(partner_iso, year)

# Remove VEN from trade flows data frame
trade_flows %>% anti_join(transaction_costs) %>% View
```

```{r}
## Comtrade search parameters
search <-
  function(partner, year) {
    data <- ct_search(
      reporters = "Guatemala",
      partners = partner,
      trade_direction = "exports",
      start_date = year,
      end_date = year,
      commod_codes = "AG4"
    )
  }

## Extraction loop
get <-
  function(partners, years) {
    data <- data.frame()
    for (year in years) {
      query <- search(partners, year)
      data <- rbind(data, query)
    }
    data %>%
      as_tibble()
  }

## Export as .rds
write <-
  function(data) {
    name <- deparse(substitute(data))
    write_rds(data, file = paste0("../Gravity model/Data/Exports raw/", name, ".rds"))
  }
```

```{r}
arg <-
  get(partners = c("Argentina"),
      years = c(1995:2020))

write(arg)
```

```{r}
arg %>% 
  filter(year != 1994) %>% 
  anti_join(trade_flows)
```

```{r}
test <- read_rds(here("Data", "Exports raw", "sa_exports_snd.rds"))
```

Concord

```{r}
library(concord_hs)
```

```{r}
concord_hs(sourcevar = c("1206", "8546"),
           origin = "HS5", destination = "HS4",
           dest.digit = 4, all = TRUE)
```
