```{r}
pacman::p_load(tidyverse, here)
```

# General data wrangling

## (a) Trade data frame

### Loading exports and imports

```{r}
# Exports
setwd(here("Data", "Exports raw"))

exports_raw <- 
  dir(pattern = "*.rds") %>% 
  map(read_rds) %>% 
  reduce(bind_rows)

# Imports
setwd(here("Data", "Imports raw"))

imports_raw <-
  dir(pattern = "*.rds") %>%
  map(read_rds) %>%
  reduce(bind_rows)

setwd(here())
```

### Binding and cleaning

```{r}
trade <- 
  bind_rows(exports_raw, imports_raw) %>% 
  select_if(~ !any(is.na(.))) %>% 
  select(-c(classification, period, period_desc, 
            is_leaf_code, trade_flow_code, flag, 
            aggregate_level, reporter_code, partner_code)) %>% 
  group_by(trade_flow) %>% 
  arrange(year, trade_flow, partner, commodity) %>% 
  mutate(partner = case_when(
    partner == "Dominican Rep." ~ "Dominican Republic",
    partner == "Bolivia (Plurinational State of)" ~ "Bolivia",
    TRUE ~ partner
  )) %>% 
  ungroup()
```

### Writing tibble

```{r}
write_rds(trade, file = paste0(here("Data", "Main data frames"), "/trade.rds"))
```

## (b) Country names data frame

### Loading ISO codes from Github

UN geoscheme: <https://en.wikipedia.org/wiki/United_Nations_geoscheme#Americas>

```{r}
codes <-
  read_csv("https://git.io/v564u") %>%
  select(partner = name,
         partner_iso = `alpha-3`,
         subregions = `sub-region`,
         int_region = `intermediate-region`) %>% 
  mutate(name = case_when(
    partner == "Venezuela (Bolivarian Republic of)" ~ "Venezuela", 
    partner == "Bolivia (Plurinational State of)" ~ "Bolivia",
    TRUE ~ partner 
  ))
```

### Joining with country names in the `trade` data frame

```{r}
names <- 
  tribble(~partner,
        # Central America and Mexico
        "Belize", "Costa Rica", "Panama", "Honduras",
        "Nicaragua", "El Salvador", "Mexico",
        
        # South America
        "Argentina", "Bolivia",  "Brazil", "Chile",
        "Colombia", "Ecuador", "Venezuela", "Guyana",
        "Paraguay", "Peru", "Uruguay", "Suriname",
        
        # Caribbean
        "Dominican Republic", "Cuba", "Haiti", "Trinidad and Tobago",
        "Antigua and Barbuda", "Dominica", "Grenada", "Jamaica", "Barbados",
        "Bahamas", "Saint Kitts and Nevis", "Saint Vincent and the Grenadines", 
        "Saint Lucia")

countries <- 
  codes %>% 
  inner_join(names, by = "partner") %>% 
  arrange(partner, int_region)
```

### Writing tibble

```{r}
write_csv(countries, file = paste0(here("Data", "Main data frames"), "/countries.csv"))
```

### Join example

```{r}
trade %>% left_join(countries, by = c("partner_iso", "partner"))
```

## (c) Structural gravity variables

### Import dataframes

```{r}
partners <- 
  read_rds("https://github.com/gafnts/gravity-model/blob/main/Data/World%20Bank%20raw/partners_wdi.rds?raw=true") %>% 
  select(year:iso3c, capital:latitude) %>% 
  rename("partner_iso" = iso3c)
```

```{r}
guatemala <- 
  read_rds("https://github.com/gafnts/gravity-model/blob/main/Data/World%20Bank%20raw/guatemala_wdi.rds?raw=true") %>% 
  select(year:iso3c, capital:latitude) %>% 
  rename("reporter_iso" = iso3c)
```

### Writing tibbles

```{r}
write_rds(partners, file = paste0(here("Data", "Main data frames"), "/partners.rds"))
write_rds(guatemala, file = paste0(here("Data", "Main data frames"), "/guatemala.rds"))
```
