```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, here, WDI)
```

# World Bank Development Indicators

### Names query

```{r}
as_tibble(WDIsearch("exchange")) %>% print(n = Inf)
```

## (a) Extraction functions

### Search parameters

```{r}
search <- function(country) {
  data <- WDI(
    indicator = c(
      gdp = "NY.GDP.MKTP.CD", # (current US$)
      gdp_pcap = "NY.GDP.PCAP.CD", # (current US$)
      population = "SP.POP.TOTL"
    ),
    country = country,
    start = 1995,
    end = 2020,
    extra = TRUE
  ) %>% 
    as_tibble()
}
```

### Export as .rds

```{r}
write <-
  function(data) {
    name <- deparse(substitute(data))
    write_rds(data, file = paste0(here("Data", "World Bank raw"), "/", name, ".rds"))
  }
```

## (b) Data extraction

### Countries in the main dataset

```{r}
partners <- 
  read_rds("https://github.com/gafnts/gravity-model/blob/main/Data/Main%20data%20frames/countries.rds?raw=true") %>% 
  pull(partner_iso)
```

### Extraction

```{r}
partners_wdi <- search(partners)
write(partners_wdi)
```

```{r}
guatemala_wdi <- search("GT")
write(guatemala_wdi)
```
